import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

const TOKEN_LIFETIME_DAYS = 365

// POST /api/extension/connect
// Called by the /extension-auth page after the user is logged in.
// Creates (or refreshes) a long-lived extension token and returns it.
export async function POST(request: NextRequest) {
  const session = await auth()
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Validate that the request comes from an allowed extension
  const origin = request.headers.get('origin') ?? ''
  const referer = request.headers.get('referer') ?? ''
  const isFromApp = origin.includes(process.env.AUTH_URL ?? '') || referer.includes(process.env.AUTH_URL ?? '')
  if (!isFromApp && process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const expiresAt = new Date()
  expiresAt.setDate(expiresAt.getDate() + TOKEN_LIFETIME_DAYS)

  // Upsert: one token per user (replace if expired or missing)
  const existing = await prisma.extensionToken.findFirst({
    where: { userId: session.user.id },
    orderBy: { createdAt: 'desc' },
  })

  let token: string
  if (existing && existing.expiresAt > new Date()) {
    // Refresh expiry on existing valid token
    await prisma.extensionToken.update({
      where: { id: existing.id },
      data: { expiresAt },
    })
    token = existing.token
  } else {
    // Create a new token (cuid is generated by default in the schema)
    const created = await prisma.extensionToken.create({
      data: { userId: session.user.id, expiresAt },
    })
    token = created.token
  }

  return NextResponse.json({ token })
}

// DELETE /api/extension/connect — revoke all extension tokens for the user
export async function DELETE(request: NextRequest) {
  const session = await auth()
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  await prisma.extensionToken.deleteMany({ where: { userId: session.user.id } })
  return new NextResponse(null, { status: 204 })
}
